name: Gastronomicon

author: SchnTgaiSpock

description: A Slimefun addon that adds even more food to the game. Works best with ExoticGarden

main: io.github.schntgaispock.gastronomicon.Gastronomicon

website: https://github.com/SchnTgaiSpock/Gastronomicon

version: ${project.version}

api-version: 1.16

depend:
- Slimefun

softdepend:
- SlimeHUD
- ExoticGarden
- DynaTech # For automation

commands:
  gastronomicon:
    description: /gastronomicon
    aliases: [gastro, gn]
    usage: Press [tab] for usage hints

permissions:
  gastronomicon:
    checkprofile:
      description: Ability to view your Gastronomicon profile
      default: true
    checkotherprofile:
      description: Ability to see another player's profile
      default: true
      op: true
    modifyprofile:
      description: Ability to change a player's Gastronomicon profile (add proficiencies, skills, etc.)
      default: false
      op: false
    